# Configmap containing apparmor profile for cmd-daemonset
# Conpared to the Docker default AppArmor policy, this allows access to additional files in /proc/sys/kernel which are
# required by the Cmd agent.


apiVersion: v1
kind: ConfigMap
metadata:
  name: cmd-apparmor-profile
data:
  cmd-profile: |-
    #include <tunables/global>
    
    
    profile docker-cmd flags=(attach_disconnected,mediate_deleted) {
    
      #include <abstractions/base>
    
    
      network,
      capability,
      file,
      ptrace (trace,read),
    
      deny mount,
      deny umount,
    
      deny @{PROC}/* w,
      deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
      deny @{PROC}/sys/** w,
      deny @{PROC}/sysrq-trigger rwklx,
      deny @{PROC}/kcore rwklx,
      deny @{PROC}/mem rwklx,
      deny @{PROC}/kmem rwklx, 
      deny /sys/[^f]*/** wklx,
      deny /sys/f[^s]*/** wklx,
      deny /sys/fs/[^c]*/** wklx,
      deny /sys/fs/c[^g]*/** wklx,
      deny /sys/fs/cg[^r]*/** wklx,
      deny /sys/firmware/** rwklx,
      deny /sys/kernel/security/** rwklx,
    
    }
